apiVersion: v1
kind: Pod
metadata:
  name: create-container-config-error
spec:
  containers:
  - name: test
    image: nginx
    env:
    - name: APP_CONFIG
      valueFrom:
        configMapKeyRef:
          name: missing-config
          key: app
