apiVersion: v1
kind: Pod
metadata:
  name: init-fail-test
spec:
  initContainers:
  - name: init-test
    image: busybox
    command: ["sh","-c","echo init failed; exit 1"]
  containers:
  - name: main
    image: nginx
